
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modbus:
  - name: relay_board
    type: rtuovertcp
    host: 192.168.88.19
    port: 502
    delay: 1
    timeout: 5
    retries: 3

    switches:
      - name: Relay 0
        unique_id: big_relay_0
        slave: 1
        address: 0
        write_type: coil

      - name: Relay 1
        unique_id: big_relay_1
        slave: 1
        address: 1
        write_type: coil

      - name: Relay 2
        unique_id: big_relay_2
        slave: 1
        address: 2
        write_type: coil

      - name: Relay 3
        unique_id: big_relay_3
        slave: 1
        address: 3
        write_type: coil

      - name: Relay 4
        unique_id: big_relay_4
        slave: 1
        address: 4
        write_type: coil

      - name: Relay 5
        unique_id: big_relay_5
        slave: 1
        address: 5
        write_type: coil

      - name: Relay 6
        unique_id: big_relay_6
        slave: 1
        address: 6
        write_type: coil

      - name: Relay 7
        unique_id: big_relay_7
        slave: 1
        address: 7
        write_type: coil
        
  - name: victron_cerbo
    type: tcp
    host: 192.168.88.22
    port: 502
    delay: 1
    timeout: 5

    sensors:
      - name: "Stan baterii"
        unique_id: victron_battery_soc
        address: 843
        slave: 100
        input_type: holding
        device_class: battery
        unit_of_measurement: "%"
        state_class: measurement
        data_type: uint16
        scan_interval: 10

      - name: "Victron Battery Voltage"
        unique_id: victron_battery_voltage
        address: 840
        slave: 100
        input_type: holding
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement
        data_type: uint16
        scale: 0.1
        precision: 1
        scan_interval: 10

      - name: "Victron Battery Current"
        unique_id: victron_battery_current
        address: 841
        slave: 100
        input_type: holding
        unit_of_measurement: "A"
        device_class: current
        state_class: measurement
        data_type: int16
        scale: 0.1
        precision: 1
        scan_interval: 10

      - name: "Victron Battery Power"
        unique_id: victron_battery_power
        address: 842
        slave: 100
        input_type: holding
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        data_type: int16
        scan_interval: 10

      - name: "Victron DC PV Power"
        unique_id: victron_dc_pv_power
        address: 850
        slave: 100
        input_type: holding
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        data_type: uint16
        scan_interval: 10

      - name: "Victron AC Consumption L1"
        unique_id: victron_ac_consumption_l1
        address: 817
        slave: 100
        input_type: holding
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        data_type: uint16
        scan_interval: 10

      - name: "Victron Grid Power L1"
        unique_id: victron_grid_power_l1
        address: 820
        slave: 100
        input_type: holding
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        data_type: int16
        scan_interval: 10
        
      - name: "Alternator Input Voltage"
        slave: 239
        address: 4117
        input_type: holding
        data_type: uint16
        scale: 0.01
        precision: 2
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Alternator Input Power"
        slave: 239
        address: 4118
        input_type: holding
        data_type: uint16
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        
  - name: rs485_1
    type: tcp
    host: 192.168.88.18
    port: 502
    delay: 1
    timeout: 1

    sensors:
      - name: "Boiler Temp"
        unique_id: boiler_temp
        slave: 50
        address: 160        # 0x00A0
        input_type: holding
        data_type: int16
        scale: 0.1
        precision: 1
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Water Temp"
        unique_id: water_temp
        slave: 50
        address: 161        # 0x00A1
        input_type: holding
        data_type: int16
        scale: 0.1
        precision: 1
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        
    switches:
      - name: "Water Pump Relay"
        unique_id: water_pump_relay_1
        slave: 32
        address: 0
        write_type: coil
          
      - name: "Water Relay 2"
        unique_id: water_pump_relay_2
        slave: 32
        address: 1
        write_type: coil
          
      - name: Water Valve 1
        unique_id: water_valve_relay_1
        slave: 33
        address: 0
        write_type: coil
        
      - name: Water Valve 2
        unique_id: water_valve_relay_2
        slave: 33
        address: 1
        write_type: coil
        
      - name: Water Valve 3
        unique_id: water_valve_relay_3
        slave: 33
        address: 2
        write_type: coil
        
      - name: Water Valve 4
        unique_id: water_valve_relay_4
        slave: 33
        address: 3
        write_type: coil
        