"""Constants for the EWD108 integration."""

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

DOMAIN = "ewd108"

MANUFACTURER = "EBYTE"
MODEL = "EWD108-GN0x"

CONF_BAUDRATE = "baudrate"
CONF_BYTESIZE = "bytesize"
CONF_PARITY = "parity"
CONF_STOPBITS = "stopbits"
CONF_SLAVE_ID = "slave_id"
CONF_SET_HA_LOCATION = "set_ha_location"
CONF_LOCATION_THRESHOLD_METERS = "location_threshold_meters"
CONF_CONNECTION_TYPE = "connection_type"
CONF_SERIAL_PORT = "serial_port"
CONF_DELAY = "delay"
CONF_HUB_SOURCE = "hub_source"

CONNECTION_TYPE_SERIAL = "serial"
CONNECTION_TYPE_TCP = "tcp"
CONNECTION_TYPE_RTU_OVER_TCP = "rtuovertcp"

DEFAULT_BAUDRATE = 9600
DEFAULT_BYTESIZE = 8
DEFAULT_PARITY = "N"
DEFAULT_STOPBITS = 1
DEFAULT_CONNECTION_TYPE = CONNECTION_TYPE_RTU_OVER_TCP
DEFAULT_HOST = "192.168.1.10"
DEFAULT_TCP_PORT = 502
DEFAULT_DELAY = 0.0
DEFAULT_SLAVE_ID = 1
DEFAULT_SCAN_INTERVAL = 10
DEFAULT_TIMEOUT = 3
DEFAULT_SET_HA_LOCATION = False
DEFAULT_LOCATION_THRESHOLD_METERS = 100.0

MIN_SCAN_INTERVAL = 1
MAX_SCAN_INTERVAL = 3600
MIN_SLAVE_ID = 1
MAX_SLAVE_ID = 247

RMC_REGISTER_ADDRESS = 0x0005
RMC_REGISTER_COUNT = 35
